### PR TITLE
Update AutoRest dependency to v0.17.3

### PR DESCRIPTION
**Pull request by gitfool**

### CODE REVIEW

**Review by agc93 — APPROVED** [review]
LGTM

**Comment by agc93** [comment]
Thanks for the contribution @gitfool! You should see an updated prerelease package on NuGet in 15-30 minutes.

I will update some other things and expect a stable release in the next day or two as well 😄

**Comment by agc93** [comment]
Prerelease package is now published: https://www.nuget.org/packages/Cake.AutoRest/0.2.0-unstable0010

Remember, however, that Cake doesn't automatically install NuGet dependencies so you will still need to update any `#tool` directives in your Cake scripts (or your packages.config) and clear your `tools/` folder to use the updated AutoRest in your builds.

**Comment by gitfool** [comment]
I'll probably update again after the next stable release of AutoRest. (It looks like `x-nullable` support is still only in the nightly build).

**Pull request merged**
